// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {model} from '../models';

export function BrowseMessages(arg1:string,arg2:string,arg3:string):Promise<types.BrowseMessagesResponse>;

export function ConnectToIbmmq(arg1:string,arg2:string,arg3:model.ConnectionData):Promise<boolean>;

export function ConsumeAllMessages(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function CreateIbmmqConnection(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<types.ConnectionResponse>;

export function SendBulkToQueue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean>;
