// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function BrowseMessages(arg1:string,arg2:string,arg3:string):Promise<types.BrowseMessagesResponse>;

export function ConsumeAllMessages(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SendMessageToQueue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
