// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateIbmmqConnection(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.ConnectionResponse>;
