// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQueueToChannel(arg1, arg2, arg3) {
  return window['go']['store']['queueStore']['AddQueueToChannel'](arg1, arg2, arg3);
}

export function ChangeRequestName(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['store']['queueStore']['ChangeRequestName'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateQueueManager(arg1) {
  return window['go']['store']['queueStore']['CreateQueueManager'](arg1);
}

export function DeleteQueue(arg1, arg2, arg3) {
  return window['go']['store']['queueStore']['DeleteQueue'](arg1, arg2, arg3);
}

export function DeleteRequest(arg1, arg2, arg3, arg4) {
  return window['go']['store']['queueStore']['DeleteRequest'](arg1, arg2, arg3, arg4);
}

export function GetAll() {
  return window['go']['store']['queueStore']['GetAll']();
}

export function GetChannels(arg1) {
  return window['go']['store']['queueStore']['GetChannels'](arg1);
}

export function GetQueue(arg1, arg2, arg3) {
  return window['go']['store']['queueStore']['GetQueue'](arg1, arg2, arg3);
}

export function GetQueueManager(arg1) {
  return window['go']['store']['queueStore']['GetQueueManager'](arg1);
}

export function GetQueues(arg1, arg2) {
  return window['go']['store']['queueStore']['GetQueues'](arg1, arg2);
}

export function GetRequestForQueue(arg1, arg2, arg3) {
  return window['go']['store']['queueStore']['GetRequestForQueue'](arg1, arg2, arg3);
}

export function SaveMessageRequest(arg1, arg2, arg3, arg4) {
  return window['go']['store']['queueStore']['SaveMessageRequest'](arg1, arg2, arg3, arg4);
}

export function WipeData() {
  return window['go']['store']['queueStore']['WipeData']();
}
