// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddQueueToChannel(arg1:string,arg2:string,arg3:model.Queue):Promise<void>;

export function CreateQueueManager(arg1:model.QueueManager):Promise<model.QueueManager>;

export function GetAll():Promise<Array<model.QueueManager>>;

export function GetChannels(arg1:string):Promise<Array<model.Channel>>;

export function GetQueue(arg1:string,arg2:string,arg3:string):Promise<model.Queue>;

export function GetQueueManager(arg1:string):Promise<model.QueueManager>;

export function GetQueues(arg1:string,arg2:string):Promise<Array<model.Queue>>;

export function GetRequestForQueue(arg1:string,arg2:string,arg3:string):Promise<Array<model.Request>>;

export function SaveMessageRequest(arg1:string,arg2:string,arg3:string,arg4:model.Request):Promise<void>;

export function WipeData():Promise<void>;
